version: '3'
services:
  nginx:
    build: ./docker/nginx
    container_name: 'nginx'
    ports:
      - 80:80
    volumes:
      - ./:/var/www
  vue:
    build: 
      context: .
      dockerfile: ./docker/vue/Dockerfile
    container_name: 'vue'
    ports:
      - 3000:3000
    volumes:
      - ./:/var/www
      - ./node_modules:/var/www/node_modules
  php:
    build: 
      context: .
      dockerfile: ./docker/php/Dockerfile
    container_name: php
    volumes:
      - ./:/var/www
      - ./vendor:/var/www/vendor
      - ./docker/php/php.ini:/usr/local/etc/php/php.ini
  mysql:
    image: mysql
    container_name: 'db'
    environment:
      MYSQL_DATABASE: laravel
      MYSQL_USER: root
      MYSQL_PASSWORD: password
      MYSQL_ROOT_PASSWORD: password
    ports:
      - 3306:3306
    volumes:
      - ./docker/mysql:/var/lib/mysql
